[package]
name = "arduino-blink"
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.3.4", features = ["atmega328p", "rt"] }
avr-std-stub = "1.0"

[profile.release]
lto = true